id: P72EB1F15
initial_creation_type: input
source_metadata:
  title: Dedication Series
  language: de
  description: 'A selection of prayers and texts related to the transfer or dedication
    of virtue or merit (pariṇāmana; dge ba bsngo ba), which is the seventh of the
    seven branch practices and the third of the three noble principles:'
  volume:
    c3830b1390174730a13fd7641ad70d68:
      title: The Three Noble Principles
      parent: Explanation
    d9a8fef72e2a42d3a5c9b997f3f55840:
      title: Extremely Concise Dedication
      parent: Prayers
    0316ed069ae44d258bcc19139fa082c7:
      title: Dedication (Sangye tenpa...)
      parent: Prayers
    87ab6721522a4629a9aaf388a1eb67cf:
      title: Temple Dedication Prayer
      parent: Prayers
    a4658f7e91224b14a9564d1cc817d557:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Prayers
created_at: '2022-03-01T03:23:03.024995'
last_modified_at: '2022-03-01T03:23:03.024998'
